### ISSUE TITLE
Sonatype OSS上のSNAPSHOTバージョンの利用について

### ISSUE THREAD

**Issue by PoohSunny** [tddbc/groovy_spock#9]
現在、spock-coreは[Sonatype OSS](https://oss.sonatype.org/content/repositories/snapshots/org/spockframework/spock-core/)上のSNAPSHOTバージョンを利用しています。

最新機能が利用できる反面、古いSNAPSHOTは削除されてしまうので、気をつけてウォッチして追随する必要があり、やや手間がかかります。そのため、SNAPSHOTではなく、 [mavenCentral](http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22org.spockframework%22%20AND%20a%3A%22spock-core%22) に上がっているものを利用するように切り替えたほうがよいと思うのですが、いかがでしょうか？

ここまで書いておいて、もしかしたらこのプロジェクトにCI回した方が良いか!?、とも思いつきましたが。。。

**Comment by grimrose** [comment]
1.0が正式にリリースされたので、あえてSNAPSHOTを利用する意味もなくなったと思います。

CIについては、windows向けにappveyor、あとはtravis-ci、circle-ci、snap-ciらへんですかね。

**Comment by PoohSunny** [comment]
> 1.0が正式にリリースされたので、あえてSNAPSHOTを利用する意味もなくなったと思います。
ではmavenCentralから取得するようにしますね。

CIは、mavenCentralから取れば同種の問題は防げるので、また今度にします。

**Comment by PoohSunny** [comment]
というわけでPR送ったのでどなたかレビューとマージお願いします。

**Comment by PoohSunny** [comment]
マージされたのでこちらもクローズします。
